### ISSUE TITLE
Hi it's me ansel from summer camp at visst do you remember me?

### ISSUE THREAD

**Issue by Coconana9010** [MaxBiz100/iSee-Camera-System-1.0#2]

**Comment by Coconana9010** [comment]
![image](https://github.com/MaxBiz100/ySee-Camera-System/assets/140546536/e1ff368b-6746-452d-a3d0-ceb8b6aba2cc)

**Comment by MaxBiz100** [comment]
I do remember you. How about we email at x9643344@gmail.com
